### ISSUE TITLE
Provide AnchorController endpoint explainInstance (with selected instance)

### ISSUE THREAD

**Issue by fkoehne** [viadee/javaAnchorServer#3]
Instance could be identified through an ID to keep things simple. 
We will need this sooner or later, probably both from the UI and from a (yet to be planned) API access to the server from R or Python. :)

**Comment by AlexKroeker** [comment]
In fact, it is possible via the FeatureConditionsRequest parameter. Here you can filter the instance to be explained by setting a Feauter (e.g. ID) to a certain value. In this way, there is only one instance to choose from.
